Feature/new card
Miretpl/delta-1-frontend pull request #17
Opened 2020-12-01 21:33 UTC by raionsakana

2020-12-01 22:06 UTC, Miretpl requested changes

2020-12-01 22:06 UTC, Miretpl commented on src/app/board/view-board/list/list.component.ts
> +  visibleAddCardForm() {
Brak typu zwracanego.

2020-12-01 22:06 UTC, Miretpl commented on src/app/board/view-board/new-card/new-card.component.css
> +    max-width: 99%;
Czemu 99%?

2020-12-01 22:06 UTC, Miretpl commented on src/app/board/view-board/new-card/new-card.component.html
> +        <div class="form-group">
Potrzebujemy tutaj rozdzielenia na 2 różne divy?

2020-12-01 22:06 UTC, Miretpl commented on src/app/board/view-board/new-card/new-card.component.ts
> +  submitted = false;
Stałe, inputy, outputy, reszta.

2020-12-01 22:06 UTC, Miretpl commented on src/app/board/view-board/new-card/new-card.component.ts
> +  get getFormControls() {
Brak typu zwracanego.

2020-12-01 22:06 UTC, Miretpl commented on src/app/board/view-board/new-card/new-card.component.ts
> +        resp => console.log("Card created"),
Nie odświeżamy tablicy po dodaniu karty?

2020-12-02 20:21 UTC, raionsakana commented on src/app/board/view-board/new-card/new-card.component.css
> +    max-width: 99%;
Kwestia paska poziomego. Bez tego się pokazuje.

2020-12-02 20:21 UTC, raionsakana commented on src/app/board/view-board/list/list.component.ts
> +  visibleAddCardForm() {
Done.

2020-12-02 20:52 UTC, raionsakana commented on src/app/board/view-board/new-card/new-card.component.ts
> +  submitted = false;
Czemu inputy, outputy, a nie odwrotnie? W innych miejscach mamy kolejność output, input, więc trzymajmy się tego.

2020-12-02 20:53 UTC, raionsakana commented on src/app/board/view-board/new-card/new-card.component.ts
> +        resp => console.log("Card created"),
Odświeżamy, jest niżej.

2020-12-02 20:55 UTC, raionsakana commented on src/app/board/view-board/new-card/new-card.component.ts
> +  get getFormControls() {
Done.

2020-12-02 21:04 UTC, raionsakana commented on src/app/board/view-board/new-card/new-card.component.html
> +        <div class="form-group">
Done.

2020-12-02 21:15 UTC, Miretpl requested changes

2020-12-02 21:15 UTC, Miretpl commented on src/app/board/view-board/new-card/new-card.component.ts
> +  submitted = false;
Ja widzę że mamy np. stałe i inputy w plikach które były wcześniej utworzone. W kodzie jest bałagan także jeśli nie chcesz to można tą zmianę obecnie pominąć. W nadchodzącym sprincie jak będziemy robić refactor to można to zmienić od razu.

2020-12-02 21:15 UTC, Miretpl commented on src/app/board/view-board/new-card/new-card.component.ts
> +        resp => console.log("Card created"),
Ok, ale odświeżamy niezależnie od tego czy mamy dodaną kartę czy nie - jaki jest tego sens?

2020-12-02 21:16 UTC, Miretpl commented on src/app/board/view-board/new-card/new-card.component.css
> +    max-width: 99%;
Ok

2020-12-02 21:18 UTC, raionsakana commented on src/app/board/view-board/new-card/new-card.component.ts
> +  submitted = false;
Ok.

2020-12-02 21:20 UTC, raionsakana commented on src/app/board/view-board/new-card/new-card.component.ts
> +        resp => console.log("Card created"),
Przy tworzeniu list mamy tak samo, zmieniłem w obu.

2020-12-02 21:23 UTC, Miretpl approved these changes

2020-12-02 21:25 UTC, merged