Feature/card-edit
Miretpl/delta-1-frontend pull request #25
Opened 2020-12-06 22:37 UTC by Miretpl

2020-12-06 22:56 UTC, raionsakana requested changes

2020-12-06 22:56 UTC, raionsakana commented on src/app/board/view-board/change-board-name/change-board-name.component.ts
> +        || event.code == this.ARROW_UP_CODE || event.code == this.ARROW_DOWN_CODE;
Zróbmy z tego metodę.

2020-12-06 22:56 UTC, raionsakana commented on src/app/card/view-card/change-card-description/change-card-description.component.html
> +</div>
To jest `form` bez forma?

2020-12-06 22:56 UTC, raionsakana commented on src/app/card/view-card/change-card-name/change-card-name.component.ts
> +        || event.code == this.ARROW_UP_CODE || event.code == this.ARROW_DOWN_CODE;
Zróbmy z tego metodę.

2020-12-06 22:56 UTC, raionsakana commented on src/app/card/view-card/view-card.component.css
> +    left: 0;
Tak się tego nie zapisuje. Coś albo pozycjonujemy góra lub dól i prawo lub lewo.

2020-12-06 22:56 UTC, raionsakana commented on src/app/card/view-card/view-card.component.ts
> +  insideClick: boolean;
`inside click`?

2020-12-06 22:59 UTC, Miretpl commented on src/app/board/view-board/change-board-name/change-board-name.component.ts
> +        || event.code == this.ARROW_UP_CODE || event.code == this.ARROW_DOWN_CODE;
Poprawione.

2020-12-06 22:59 UTC, Miretpl commented on src/app/card/view-card/change-card-description/change-card-description.component.html
> +</div>
Używam tutaj tylko stylu, który `form-control` daje w bootstrapie. Same formy nie są tutaj potrzebne.

2020-12-06 22:59 UTC, Miretpl commented on src/app/card/view-card/change-card-name/change-card-name.component.ts
> +        || event.code == this.ARROW_UP_CODE || event.code == this.ARROW_DOWN_CODE;
Poprawione.

2020-12-06 23:17 UTC, Miretpl commented on src/app/card/view-card/view-card.component.css
> +    left: 0;
Poprawione.

2020-12-06 23:29 UTC, Miretpl commented on src/app/card/view-card/view-card.component.ts
> +  insideClick: boolean;
Potrzebujemy wykrywać czy kliknięcie nastąpiło wewnątrz okna pojawiającego się (card view). Jeśli tak to je ignorujemy a jeśli nie to zamykamy okno.

2020-12-06 23:48 UTC, raionsakana requested changes

2020-12-06 23:48 UTC, raionsakana commented on src/app/board/view-board/change-board-name/change-board-name.component.ts
>    private MAX_NAME_LENGTH: number = 32;
Te kodu są chyba w kilku miejscach, można by je wrzucić w jedno miejsce.

2020-12-06 23:48 UTC, raionsakana commented on src/app/board/view-board/change-board-name/change-board-name.component.ts
>    private MAX_NAME_LENGTH: number = 32;
A nie, to chyba wciąż to samo review :D

2020-12-06 23:48 UTC, raionsakana commented on src/app/board/view-board/change-board-name/change-board-name.component.ts
> +      return this.isAllowedCode(event.code);
Może `isAllowedKeyCode`?

2020-12-06 23:48 UTC, raionsakana commented on src/app/card/view-card/change-card-description/change-card-description.component.html
> +</div>
To jest bardziej kwestia struktury kodu. Bo mamy submit, a nie mamy forma.

2020-12-06 23:48 UTC, raionsakana commented on src/app/card/view-card/view-card.component.ts
> +  insideClick: boolean;
Bardziej chodzi mi o nazwę, nie jest jednoznaczna.

2020-12-06 23:51 UTC, Miretpl commented on src/app/card/view-card/change-card-description/change-card-description.component.html
> +</div>
Poprawione.

2020-12-06 23:52 UTC, Miretpl commented on src/app/card/view-card/view-card.component.ts
> +  insideClick: boolean;
Poprawione.

2020-12-06 23:55 UTC, Miretpl commented on src/app/board/view-board/change-board-name/change-board-name.component.ts
>    private MAX_NAME_LENGTH: number = 32;
Poprawione.

2020-12-06 23:58 UTC, Miretpl commented on src/app/board/view-board/change-board-name/change-board-name.component.ts
> +      return this.isAllowedCode(event.code);
Poprawione.

2020-12-07 09:45 UTC, raionsakana requested changes

2020-12-07 09:45 UTC, raionsakana commented on src/app/board/view-board/change-board-name/change-board-name.component.ts
> +    if (event.code == consts.ENTER_CODE || event.code == consts.NUMPAD_ENTER_CODE) {
Czy to powinna być ta sama paczka stałych?

2020-12-07 10:01 UTC, Miretpl commented on src/app/board/view-board/change-board-name/change-board-name.component.ts
> +    if (event.code == consts.ENTER_CODE || event.code == consts.NUMPAD_ENTER_CODE) {
Stałe to stałe. Ogólnie można by wydzielić na endpoints i consts żeby rozróżnić - to zrobiłem.

2020-12-07 10:07 UTC, raionsakana requested changes

2020-12-07 10:07 UTC, raionsakana commented on src/app/card/view-card/change-card-name/change-card-name.component.ts
> +    if (event.code == consts.ENTER_CODE || event.code == consts.NUMPAD_ENTER_CODE) {
Tu nie jakieś `keys`?

2020-12-07 10:07 UTC, raionsakana commented on src/app/config/consts.ts
>  export const consts = {
Jako że mamy tutaj kody przycisków, nazwa `consts` jest niejednoznaczna.

2020-12-07 10:11 UTC, Miretpl commented on src/app/config/consts.ts
>  export const consts = {
Wydzieliłem z consts keys.

2020-12-07 10:11 UTC, Miretpl commented on src/app/card/view-card/change-card-name/change-card-name.component.ts
> +    if (event.code == consts.ENTER_CODE || event.code == consts.NUMPAD_ENTER_CODE) {
Poprawione.

2020-12-07 10:45 UTC, raionsakana approved these changes

2020-12-07 10:46 UTC, merged