Hotfix
Miretpl/delta-1-frontend pull request #34
Opened 2020-12-17 13:05 UTC by Miretpl

2020-12-18 21:54 UTC, Miretpl commented
**Fixed:**
1. no auth token in requests
2. refresh board list after board creation
3. select text with mouse during card creation
4. proper card delete endpoint
5. proper dueDate format
6. edit description window visibility with data
7. show up isArchived lists
8. duplicated board after new created
9. check if dueDate is null
10. proper cursor over the change list name
11. error with length
12. drag and drop
13. update list board after board creation
14. drag list over card, list ... element or new card
15. cursor pointer over a card in a list element
16. create card size when active
17. card description edit shows up and the due date
18. overflows on view board
19. bg size of add list during error
20. form submission cancelled during invite user to board
21. request to backend when drag&drop does not change the position of elements
22. the card does not refresh after card creation
23. refresh card after due date save
24. NaN during update due date value
25. update card information after update
26. update board after delete and close card window
27. length error during close on change description
28. no description edit window open when desc is empty
29. refresh board after card creation

**Updated:**
1. colour button in an invite to user
2. add center, break-word and margin to change board name

**Refactored:**
1. view-board
2. create-board
3. view-list
4. view-card
5. change-due-date
6. login
7. register

2021-01-05 15:57 UTC, raionsakana requested changes

2021-01-05 15:57 UTC, raionsakana commented on src/app/board/create-board/create-board.component.ts
> +  onSubmit(): void{
Brakująca spacja: `void{` na `void {`.

2021-01-05 15:57 UTC, raionsakana commented on src/app/board/view-board/change-board-name/change-board-name.component.html
> +<h5 class="text-center text-break rounded px-3 py-2 my-1" #newName contenteditable (keydown)="checkCharacters($event, newName.innerText)" (blur)="updateName(newName.innerText)">{{ name }}</h5>
Nazwy nie miały iść do lewej?

2021-01-05 15:57 UTC, raionsakana commented on src/app/board/view-board/invite-user-to-board/invite-user-to-board.component.html
> +        <button type="button" class="btn btn-primary w-100" (click)="inviteUserToBoard()">Send invitation</button>
Niebieski?

2021-01-05 15:57 UTC, raionsakana commented on src/app/card/view-card/change-due-date/change-due-date.component.ts
> +    return `${this.calendarModel.year}-${month}-${day} ${hour}:${minute}:00`;
Nie będziemy obsługiwać sekund? Może lepiej całkowicie z nich zrezygnować i nie wyświetlać nigdzie?

2021-01-05 15:57 UTC, raionsakana commented on src/app/card/view-card/view-card.component.html
> +      <div *ngIf="isArchived" class="col-md-12 p-3 mb-2 bg-warning text-dark">
Dlaczego zmieniłeś `[hidden]` na `*ngIf`?

_(to się powtarza w całym pliku)_

2021-01-05 15:57 UTC, raionsakana commented on src/app/card/view-card/view-card.component.ts
> +        this.visibleChangeDescriptionField = this.description == null || this.description == "" ? true : false;
Może wypchnąć to do metody?

2021-01-05 15:59 UTC, Miretpl commented on src/app/board/view-board/change-board-name/change-board-name.component.html
> +<h5 class="text-center text-break rounded px-3 py-2 my-1" #newName contenteditable (keydown)="checkCharacters($event, newName.innerText)" (blur)="updateName(newName.innerText)">{{ name }}</h5>
Przywróciłem wersję początkową tutaj. Wielkość okna jest do tekstu także text-center wygląda lepiej.

2021-01-05 16:00 UTC, Miretpl commented on src/app/board/view-board/invite-user-to-board/invite-user-to-board.component.html
> +        <button type="button" class="btn btn-primary w-100" (click)="inviteUserToBoard()">Send invitation</button>
Z tego co pamiętam to zmieniłem to ze względu na brak spójności z innymi przyciskami. Minęły prawie 3 tygodnie, musiałbym poklikać i sprawdzić czy na pewno dla tego.

2021-01-05 16:01 UTC, Miretpl commented on src/app/card/view-card/change-due-date/change-due-date.component.ts
> +    return `${this.calendarModel.year}-${month}-${day} ${hour}:${minute}:00`;
Sekundy nie są nigdzie wyświetlane, ale być muszą - wymaga ich backend.

2021-01-05 16:02 UTC, Miretpl commented on src/app/card/view-card/view-card.component.html
> +      <div *ngIf="isArchived" class="col-md-12 p-3 mb-2 bg-warning text-dark">
Hidden ukrywa element. NgIf tworzy nowy przy spełnieniu warunku, czyli inicjalizuje komponent.

2021-01-05 16:08 UTC, Miretpl commented on src/app/board/create-board/create-board.component.ts
> +  onSubmit(): void{
Poprawione.

2021-01-05 16:20 UTC, Miretpl commented on src/app/card/view-card/view-card.component.ts
> +        this.visibleChangeDescriptionField = this.description == null || this.description == "" ? true : false;
Wypchnięte.

2021-01-05 17:26 UTC, raionsakana approved these changes

2021-01-05 17:27 UTC, merged