Feature/users and card history
Miretpl/delta-1-frontend pull request #35
Opened 2021-01-10 17:47 UTC by raionsakana

2021-01-10 17:47 UTC, raionsakana commented
@Miretpl  miałem problem z jednym scrollem. Opisałem w pliku css. Według tego, co znalazłem, to żeby scroll działał, jedna z wysokości w hierarchii musi być w pikselach. Dziwne, ale może spotkałeś się już z tym?

2021-01-11 00:59 UTC, Miretpl requested changes

2021-01-11 00:59 UTC, Miretpl commented on src/app/board/view-board/show-users/show-users.component.ts
> +
Za dużo enterów.

2021-01-11 00:59 UTC, Miretpl commented on src/app/card/view-card/show-activity/show-activity.component.css
> +}
Dokładnie to samo jest w show-users.component.css, czy któryaś kopia nie jest zbędna?

2021-01-11 00:59 UTC, Miretpl commented on src/app/card/view-card/show-activity/show-activity.component.ts
> +      this.date = `${creationTimeTmp[0]} at ${timeTmp[0]}:${timeTmp[1]}`;
Wyrzuciłbym do metody.

2021-01-11 10:01 UTC, raionsakana commented on src/app/card/view-card/show-activity/show-activity.component.css
> +}
Nie, obie są w sumie potrzebne. Jedna jest w menu u góry, a druga w widoku historii. Myślałem, czy nie wykorzystać tego samego komponentu, ale zrezygnowałem, ponieważ wersja z menu, gdyby aplikacja była robiona dalej, byłaby bardziej rozbudowana. Także niech zostanie tak jak jest.

2021-01-11 10:04 UTC, raionsakana commented on src/app/card/view-card/show-activity/show-activity.component.ts
> +      this.date = `${creationTimeTmp[0]} at ${timeTmp[0]}:${timeTmp[1]}`;
Done.

2021-01-11 10:04 UTC, raionsakana commented on src/app/board/view-board/show-users/show-users.component.ts
> +
Done.

2021-01-11 11:02 UTC, merged